services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  inventory-api:
    build: ./inventory
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./inventory:/app
    networks:
      - app-network

  checkout-api:
    build: ./checkout
    container_name: checkout-api
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - inventory-api
    volumes:
      - ./checkout:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
